// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummonerMatch;

#nullable disable

namespace SummonerMatch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240909213923_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SummonerMatch.Equipo", b =>
                {
                    b.Property<int>("IdEquipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FkPartida")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorAdc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorJungle")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorMid")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorSupport")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorTop")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEquipo");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("SummonerMatch.Partida", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FkRango")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkTipoPartida")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkTorneo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkUsuarioCreador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JugadorAdc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorJungle")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorMid")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorSupport")
                        .HasColumnType("TEXT");

                    b.Property<string>("JugadorTop")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumJugadores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPartida");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("SummonerMatch.Posicion", b =>
                {
                    b.Property<int>("IdPosicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePosicion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPosicion");

                    b.ToTable("Posicion");
                });

            modelBuilder.Entity("SummonerMatch.Rango", b =>
                {
                    b.Property<int>("IdRango")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRango")
                        .HasColumnType("TEXT");

                    b.HasKey("IdRango");

                    b.ToTable("Rango");
                });

            modelBuilder.Entity("SummonerMatch.Region", b =>
                {
                    b.Property<int>("IdRegion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRegion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdRegion");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("SummonerMatch.TipoPartida", b =>
                {
                    b.Property<int>("IdTipoPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreTipo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoPartida");

                    b.ToTable("TipoPartida");
                });

            modelBuilder.Entity("SummonerMatch.Torneo", b =>
                {
                    b.Property<int>("IdTorneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadEquipos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTorneo");

                    b.ToTable("Torneo");
                });

            modelBuilder.Entity("SummonerMatch.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contrasena")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EsAdministrador")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkPosicion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkRango")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkRegion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkValoracion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagenPerfil")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioLoL")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SummonerMatch.Valoracion", b =>
                {
                    b.Property<int>("IdValoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CantidadValoraciones")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("PuntuacionMedia")
                        .HasColumnType("REAL");

                    b.HasKey("IdValoracion");

                    b.ToTable("Valoracion");
                });
#pragma warning restore 612, 618
        }
    }
}
